namespace Battle.Source.Abilities
{
    using System;
    using System.Collections.Generic;
    using Core.Battle.Abilities;
    using Core.Data.AbilityData;
    using Targeting;

    public partial class AbilityProvider
    {
        private readonly Dictionary<string, Func<AbilityBaseData, IAbility>> _abilityFactories = new()
        {
            ["Ability_Ice_Shards"] = data => new IceShards.IceShards(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("projectiles", 3),
                data.AbilityProperties.GetValueOrDefault("shrapnelDamage", 50f),
                data.AbilityProperties.GetValueOrDefault("shrapnelWeaponDamageScale", 0.15f),
                data.AbilityProperties.GetValueOrDefault("shrapnelSpellDamageScale", 0.55f),
                data.AbilityProperties.GetValueOrDefault("secondStageDamage", 120f),
                data.AbilityProperties.GetValueOrDefault("secondStageWeaponDamageScale", 0.35f),
                data.AbilityProperties.GetValueOrDefault("secondStageSpellDamageScale", 1.2f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Series_Of_Attacks"] = data => new SeriesOfAttacks.SeriesOfAttacks(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("minAttacks", 2),
                (int)data.AbilityProperties.GetValueOrDefault("maxAttacks", 5),
                data.AbilityProperties.GetValueOrDefault("damageMultiplier", 1.3f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Poison_Explosion"] = data => new PoisonExplosion.PoisonExplosion(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("executionThreshold", 42),
                data.AbilityProperties.GetValueOrDefault("multiplier", 0f))
            {
                Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data),
            },
            ["Ability_Poison_Coating"] = data => new PoisonCoating.PoisonCoating(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("buffDuration", 3),
                (int)data.AbilityProperties.GetValueOrDefault("poisonDuration", 5),
                data.AbilityProperties.GetValueOrDefault("poisonMultiplier", 0.45f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Jar_Of_Poison"] = data => new JarOfPoison.JarOfPoison(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                3,
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Increasing_Pressure"] = data => new IncreasingPressure.IncreasingPressure(
                data.Tags,
                data.CostValue,
                data.Cooldown,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("attacks", 5),
                data.AbilityProperties.GetValueOrDefault("damageMultiplier", 0.15f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Dark_Shroud"] = data => new DarkShroud.DarkShroud(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("stacks", 3),
                data.AbilityProperties.GetValueOrDefault("healthRegen", 0.05f),
                data.AbilityProperties.GetValueOrDefault("lightStepValue", 0.15f),
                (int)data.AbilityProperties.GetValueOrDefault("duration", 3),
                data.AbilityProperties.GetValueOrDefault("effectiveness", 1f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Head_Butt"] = data => new HeadButt.HeadButt(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("stunDuration", 1),
                (int)data.AbilityProperties.GetValueOrDefault("attacks", 1),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Ice_Block"] = data => new IceBlock.IceBlocks(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("stunDuration", 1),
                (int)data.AbilityProperties.GetValueOrDefault("witheringDuration", 3),
                (int)data.AbilityProperties.GetValueOrDefault("witheringMaxStacks", 3),
                data.AbilityProperties.GetValueOrDefault("witheringValue", 0.15f),
                (int)data.AbilityProperties.GetValueOrDefault("extraBlocks", 3),
                data.AbilityProperties.GetValueOrDefault("extraBlockDamagePercent", 0.5f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Overload"] = data => new Overload.Overload(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                data.AbilityProperties.GetValueOrDefault("manaBurnPercent", 0.25f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Chain_Lightning"] = data => new ChainLightning.ChainLightning(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("jumps", 2),
                data.AbilityProperties.GetValueOrDefault("damageFalloff", 0.25f),
                data.AbilityProperties.GetValueOrDefault("stageThreeFalloffReduction", 0.15f),
                data.AbilityProperties.GetValueOrDefault("stageFourLastJumpMultiplier", 2f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Ice_Aegis"] = data => new IceAegis.IceAegis(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.AbilityProperties.GetValueOrDefault("barrierBase", 300f),
                data.AbilityProperties.GetValueOrDefault("perIntelligenceScale", 35f),
                (int)data.AbilityProperties.GetValueOrDefault("duration", 3),
                data.AbilityProperties.GetValueOrDefault("stageTwoScaleBonus", 15f),
                (int)data.AbilityProperties.GetValueOrDefault("clumsinessDuration", 3),
                (int)data.AbilityProperties.GetValueOrDefault("clumsinessMaxStacks", 5),
                data.AbilityProperties.GetValueOrDefault("clumsinessValue", 0.15f),
                (int)data.AbilityProperties.GetValueOrDefault("freezeDuration", 1),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Armageddon"] = data => new Armageddon.Armageddon(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                data.AbilityProperties.GetValueOrDefault("secondDamage", 600f),
                data.AbilityProperties.GetValueOrDefault("secondWeaponScale", 1.2f),
                data.AbilityProperties.GetValueOrDefault("secondSpellScale", 1.2f),
                data.AbilityProperties.GetValueOrDefault("thirdDamage", 1000f),
                data.AbilityProperties.GetValueOrDefault("thirdWeaponScale", 1.8f),
                data.AbilityProperties.GetValueOrDefault("thirdSpellScale", 1.8f),
                data.AbilityProperties.GetValueOrDefault("stage1HpCost", 0.05f),
                data.AbilityProperties.GetValueOrDefault("stage2HpCost", 0.15f),
                data.AbilityProperties.GetValueOrDefault("stage3HpCost", 0.30f),
                (int)data.AbilityProperties.GetValueOrDefault("stunDuration", 2),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Porcupine"] = data => new Porcupine.Porcupine(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("duration", 3),
                data.AbilityProperties.GetValueOrDefault("damageReturn", 0.25f),
                data.AbilityProperties.GetValueOrDefault("armorReturn", 0.15f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Sacrifice"] = data => new Sacrifice.Sacrifice(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.AbilityProperties.GetValueOrDefault("sacrificePercent", 0.15f),
                data.AbilityProperties.GetValueOrDefault("ratePerHundred", 0.01f),
                (int)data.AbilityProperties.GetValueOrDefault("charges", 1),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Berserk_Fury"] = data => new BerserkFury.BerserkFury(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                (int)data.AbilityProperties.GetValueOrDefault("furyDuration", 3),
                data.AbilityProperties.GetValueOrDefault("furyHealthPercent", 0.05f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Ares_Blessing"] = data => new AresBlessing.AresBlessing(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("duration", 3),
                data.AbilityProperties.GetValueOrDefault("healthBonus", 0.3f),
                data.AbilityProperties.GetValueOrDefault("recoveryBonus", 0.3f),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Double_Strike"] = data => new DoubleStrike.DoubleStrike(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                data.Damage,
                data.WeaponDamageScale,
                data.SpellDamageScale,
                data.AbilityProperties.GetValueOrDefault("secondDamage", 60f),
                data.AbilityProperties.GetValueOrDefault("secondWeaponDamageScale", 1f),
                data.AbilityProperties.GetValueOrDefault("secondSpellDamageScale", 0.25f),
                data.AbilityProperties.GetValueOrDefault("armorReduce", 0.15f),
                data.AbilityProperties.GetValueOrDefault("evadeReduce", 0.15f),
                (int)data.AbilityProperties.GetValueOrDefault("debuffDuration", 3),
                (int)data.AbilityProperties.GetValueOrDefault("debuffMaxStacks", 3),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), },
            ["Ability_Critical_Calculation"] = data => new CriticalCalculation.CriticalCalculation(
                data.Tags,
                data.Cooldown,
                data.CostValue,
                (int)data.AbilityProperties.GetValueOrDefault("buffStacks", 3),
                (int)data.AbilityProperties.GetValueOrDefault("additionalBuffDuration", 1),
                data.CostsType) { Stance = data.Stance, MasteryLevel = data.MasteryLevel, Targeting = TargetingStrategyFactory.From(data), }
        };
    }
}
