<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Data\BaseAbilityData.json" />
    <Content Include="Source\Localization\en.po" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="Stateless" Version="5.20.1" />
    <PackageReference Update="Godot.SourceGenerators" Version="4.7.0" />
    <PackageReference Update="GodotSharp" Version="4.7.0" />
  </ItemGroup>
</Project>