<Project Sdk="Godot.NET.Sdk/4.7.0">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Serilog" Version="4.3.1" />
    <PackageReference Update="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Update="GodotSharp" Version="4.7.0" />
    <PackageReference Update="Godot.SourceGenerators" Version="4.7.0" />
    <PackageReference Update="GodotSharpEditor" />
    <PackageReference Update="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
</Project>