// AUTO-GENERATED by GenerateTagConstants. Do not edit.
namespace Core.Constants
{
    using System;
    using System.Collections.Generic;

    public static class TagConstants
    {
        public const string Common = "common";
        public const string Rarity = "rarity";
        public const string Uncommon = "uncommon";
        public const string Rare = "rare";
        public const string Epic = "epic";
        public const string Legendary = "legendary";
        public const string Mythic = "mythic";
        public const string Crafting = "crafting";
        public const string Fabric = "fabric";
        public const string Silk = "silk";
        public const string Velvet = "velvet";
        public const string Wool = "wool";
        public const string Linen = "linen";
        public const string Steel = "steel";
        public const string Iron = "iron";
        public const string Bronze = "bronze";
        public const string Copper = "copper";
        public const string Gold = "gold";
        public const string Adamantine = "adamantine";
        public const string Mythril = "mythril";
        public const string Leather = "leather";
        public const string Fur = "fur";
        public const string Chitin = "chitin";
        public const string Gem = "gem";
        public const string Ruby = "ruby";
        public const string Sapphire = "sapphire";
        public const string Emerald = "emerald";
        public const string Topaz = "topaz";
        public const string Diamond = "diamond";
        public const string Amethyst = "amethyst";
        public const string Moonstone = "moonstone";
        public const string Opal = "opal";
        public const string Bloodstone = "bloodstone";
        public const string Essence = "essence";
        public const string Lesser = "lesser";
        public const string Greater = "greater";
        public const string Existence = "existence";
        public const string Decease = "decease";
        public const string Equipment = "equipment";
        public const string Weapon = "weapon";
        public const string Dagger = "dagger";
        public const string Sword = "sword";
        public const string Axe = "axe";
        public const string Wand = "wand";
        public const string Staff = "staff";
        public const string Category = "category";
        public const string Heavy = "heavy";
        public const string Light = "light";
        public const string Cloth = "cloth";
        public const string Type = "type";
        public const string Boots = "boots";
        public const string Gloves = "gloves";
        public const string Helmet = "helmet";
        public const string Belt = "belt";
        public const string BodyArmor = "bodyarmor";
        public const string Cloak = "cloak";
        public const string Ring = "ring";
        public const string Amulet = "amulet";

        public static readonly HashSet<string> AllTags = new(StringComparer.Ordinal)
    {
        "common",
        "rarity",
        "uncommon",
        "rare",
        "epic",
        "legendary",
        "mythic",
        "crafting",
        "fabric",
        "silk",
        "velvet",
        "wool",
        "linen",
        "steel",
        "iron",
        "bronze",
        "copper",
        "gold",
        "adamantine",
        "mythril",
        "leather",
        "fur",
        "chitin",
        "gem",
        "ruby",
        "sapphire",
        "emerald",
        "topaz",
        "diamond",
        "amethyst",
        "moonstone",
        "opal",
        "bloodstone",
        "essence",
        "lesser",
        "greater",
        "existence",
        "decease",
        "equipment",
        "weapon",
        "dagger",
        "sword",
        "axe",
        "wand",
        "staff",
        "category",
        "heavy",
        "light",
        "cloth",
        "type",
        "boots",
        "gloves",
        "helmet",
        "belt",
        "bodyarmor",
        "cloak",
        "ring",
        "amulet",
    };

        public static bool HasTag(string tag) => tag != null && AllTags.Contains(tag);

        public static bool HasAnyTag(IEnumerable<string> tags)
        {
            if (tags == null) return false;
            foreach (var t in tags) if (HasTag(t)) return true;
            return false;
        }

        public static bool HasAllTags(IEnumerable<string> tags)
        {
            if (tags == null) return false;
            foreach (var t in tags) if (!HasTag(t)) return false;
            return true;
        }

        public static IReadOnlyCollection<string> GetAll() => AllTags;
    }
}
