namespace LastBreath.Addons.Tools.TagGenerator
{
	using System.IO;
	using System.Linq;
	using System.Text;
	using Core;
	using Godot;

	[Tool]
	[GlobalClass]
	public partial class GenerateTagConst : EditorScript
	{
		private string _path = FilePaths.TagResourcePath;

		private string _outputPath = FilePaths.TagConstPath;

		public override void _Run()
		{
			var reg = ResourceLoader.Load<TagRegistry>(_path);
			if (reg == null)
			{
				GD.PrintErr("TagRegistry not found at: " + _path);
				return;
			}

			var tags = reg.AllTags?.Where(t => t != null && !string.IsNullOrEmpty(t.Id)).ToArray() ?? [];

			var sb = new StringBuilder();
			sb.AppendLine("// AUTO-GENERATED by GenerateTagConstants. Do not edit.");
			sb.AppendLine("namespace Core.Constants");
			sb.AppendLine("{");
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine();
			sb.AppendLine("public static class TagConstants");
			sb.AppendLine("{");

			// const per tag
			foreach (var t in tags)
			{
				sb.AppendLine($"\tpublic const string {t.DisplayName} = \"{t.Id}\";");
			}
			sb.AppendLine();

			// AllTags array
			sb.AppendLine($"\tpublic static readonly HashSet<string> AllTags = new(StringComparer.Ordinal)");
			sb.AppendLine($"\t{{");
			foreach (var v in tags)
				sb.AppendLine($"\t\t\"{v.Id.Replace("\"", "\\\"")}\",");
			sb.AppendLine($"\t}};");


			sb.AppendLine();
			sb.AppendLine($"\tpublic static bool HasTag(string tag) => tag != null && AllTags.Contains(tag);");
			sb.AppendLine();
			sb.AppendLine($"\tpublic static bool HasAnyTag(IEnumerable<string> tags)");
			sb.AppendLine($"\t{{");
			sb.AppendLine($"\t\tif (tags == null) return false;");
			sb.AppendLine($"\t\tforeach (var t in tags) if (HasTag(t)) return true;");
			sb.AppendLine($"\t\treturn false;");
			sb.AppendLine($"\t}}");
			sb.AppendLine();
			sb.AppendLine($"\tpublic static bool HasAllTags(IEnumerable<string> tags)");
			sb.AppendLine($"\t{{");
			sb.AppendLine($"\t\tif (tags == null) return false;");
			sb.AppendLine($"\t\tforeach (var t in tags) if (!HasTag(t)) return false;");
			sb.AppendLine($"\t\treturn true;");
			sb.AppendLine($"\t}}");
			sb.AppendLine();
			sb.AppendLine($"\tpublic static IReadOnlyCollection<string> GetAll() => AllTags;");
			sb.AppendLine("\t}");
			sb.AppendLine("}"); // end class

			// Ensure folder exists and write file
			var fsPath = Path.Combine(_outputPath + "TagConstants.cs");
			var dir = Path.GetDirectoryName(_outputPath);
			if (dir != null && !Directory.Exists(dir)) Directory.CreateDirectory(dir);

			File.WriteAllText(fsPath, sb.ToString());
			GD.Print("TagConstants generated: " + _outputPath);
		}

		private string ToConstName(string id)
		{
			var sb = new StringBuilder();
			foreach (var c in id)
				sb.Append(char.IsLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_');
			return sb.ToString();
		}
	}
}
